// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackgroundSelection =
  | { kind: 'built_in_shader'; id: string }
  | { kind: 'pixabay' }
  | { kind: 'custom'; id: string };
