// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomBackgroundKind } from './CustomBackgroundKind';
import type { CustomBackgroundSource } from './CustomBackgroundSource';

export type CustomBackground = {
  id: string;
  name: string;
  background_type: CustomBackgroundKind;
  source: CustomBackgroundSource;
};
