// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CustomBackgroundSource =
  | { kind: 'managed'; file_name: string }
  | { kind: 'url'; url: string };
