// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FavoriteRecord = {
  profile: string;
  song_hash: string;
  favorited_at: bigint;
};
