// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryMenuFilters = { artist: string | null, album: string | null, playlist: string | null, query: string | null, status: string | null, transcript_source: string | null, search: string | null, 
/**
 * User-facing browse: matches `songs.genre` exactly. `None` and `Some("")`
 * both mean "no genre filter".
 */
genre: string | null, 
/**
 * User-facing browse: `A`-`Z` filters artists by first letter, `#` is
 * the sentinel for non-letter starts (digits, punctuation,
 * whitespace). `None` means "no letter filter".
 */
first_letter: string | null, };
