// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata for a single saved recording. The audio bytes themselves live
 * alongside the index as `<id>.wav` inside the data folder.
 */
export type RecordingRecord = { id: string, 
/**
 * Active profile at save time. Mirrors `ScoreRecord.profile` so the
 * existing leaderboard/profile views stay consistent.
 */
profile: string, song_hash: string, 
/**
 * Song title + artist as captured by the client. Stored on the row
 * itself so the history list can render even after the song entry
 * in `songs.db` is removed.
 */
song_title: string, song_artist: string, score: number, duration_secs: number, sample_rate: number, 
/**
 * Unix seconds at which the take ended (matches `ScoreRecord.played_at`
 * exactly when both rows are written from the same `usePlaybackResult`
 * call). Defaults to `0` for legacy rows so older recordings still load.
 */
played_at: bigint, 
/**
 * Unix seconds at which the recording was finalised on disk. Kept for
 * backward compatibility — for new rows this equals `played_at`.
 */
recorded_at: bigint, };
