// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordingRecord } from "./RecordingRecord";

export type RecordingStore = { recordings: Array<RecordingRecord>, };
