// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One item in the search result. Fields are kept narrow on purpose:
 * the UX only needs enough to render a card and link out. Anything
 * beyond that (channel id, publish date, view count) bloats the JSON
 * and is currently unused by the frontend.
 */
export type YouTubeHit = { video_id: string, title: string, channel_title: string, thumbnail_url: string, 
/**
 * Canonical watch URL, `https://www.youtube.com/watch?v=<video_id>`.
 * The frontend opens this in the user's default browser via
 * `tauri-plugin-opener` on desktop or `window.open` on `/guest`.
 */
watch_url: string, };
