//! The `.nge` bundle format: Nightingale's canonical, encrypted library file.
//!
//! A `.nge` is a single file that carries a song's audio plus every analysis
//! artifact (stems, cover, transcript, optional playable video) behind a
//! ChaCha20-Poly1305 envelope. It becomes the source of truth for a library
//! entry: the scanner recognises it, registers one row that points at it, and
//! the media server decrypts individual entries *in memory* at playback time —
//! nothing is ever unpacked to disk.
//!
//! # Threat model (read this before trusting it)
//!
//! The master key is composed at runtime from fragments baked into the binary.
//! That keeps the key out of the file and off `strings`/`grep`, so generic
//! tools (7-Zip, `unzip`, Archive Utility) see an opaque blob and a casual
//! explorer cannot open it. It is **obfuscation, not real cryptography**:
//! anyone who studies the Nightingale binary can recover the key. This is the
//! unavoidable cost of "offline + no passphrase + freely shareable". If strong
//! protection is ever required, it means breaking one of those three
//! constraints (device binding, a license server, or a user passphrase).
//!
//! # Binary layout (version 2, all integers little-endian)
//!
//! ```text
//! [0..4)    magic           "NGE\0"
//! [4]       version         0x02
//! [5]       cipher id       0x01  (ChaCha20-Poly1305)
//! [6..18)   header nonce    12 random bytes (salts every per-entry nonce)
//! [18..22)  manifest len    u32  — length of the encrypted manifest blob
//! [22..M)   manifest        AEAD(ciphertext + 16-byte tag)
//! [M..)     bulk            concat over entries, in manifest order, of
//!                           AEAD(ciphertext + 16-byte tag)
//! ```
//!
//! Per-entry nonces are *derived* (key + header nonce + entry name), never
//! stored, so the bulk is a tight concatenation. Each entry's ciphertext length
//! is `plaintext_len + 16`, and `plaintext_len` lives in the manifest, so entry
//! offsets are recovered by summing.

use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};

use chacha20poly1305::aead::{Aead, KeyInit};
use chacha20poly1305::{ChaCha20Poly1305, Key, Nonce};
use serde::{Deserialize, Serialize};

use crate::error::NightingaleError;

pub const NGE_MAGIC: &[u8; 4] = b"NGE\0";
pub const NGE_VERSION: u8 = 0x02;
pub const CIPHER_CHACHA20POLY1305: u8 = 0x01;

/// Bytes before the manifest blob: magic(4) + version(1) + cipher(1) +
/// nonce(12) + manifest_len(4).
const HEADER_LEN: usize = 22;
/// Poly1305 authentication tag appended to every AEAD ciphertext.
const TAG_LEN: u64 = 16;
/// A sane ceiling so a malformed/hostile header can't make us allocate wildly
/// for the manifest. Real manifests are a few KiB.
const MAX_MANIFEST_LEN: u32 = 4 * 1024 * 1024;

/// One file inside the bundle. `length` is the *plaintext* size; the stored
/// ciphertext is `length + 16`. `blake3` is the first 32 hex chars of the
/// plaintext's BLAKE3 hash (same convention as `Song::file_hash`).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ManifestEntry {
    pub name: String,
    pub length: u64,
    pub blake3: String,
}

/// The decrypted index of a bundle. `metadata` is the song's metadata verbatim
/// (title/artist/album/key/tempo/duration/…), kept as a free-form JSON object
/// so the format doesn't have to track every `Song` field.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Manifest {
    pub version: u32,
    pub file_hash: String,
    pub metadata: serde_json::Value,
    pub entries: Vec<ManifestEntry>,
}

impl Manifest {
    pub fn entry(&self, name: &str) -> Option<&ManifestEntry> {
        self.entries.iter().find(|e| e.name == name)
    }
}

/// Cheap sniff: does this look like a `.nge`? Checks the magic only, so it's
/// safe to call on the first few bytes of any file.
pub fn is_nge(bytes: &[u8]) -> bool {
    bytes.len() >= 4 && &bytes[..4] == NGE_MAGIC
}

// ─── Key composition ────────────────────────────────────────────────────────
//
// The master key is NOT written in source. 64 bytes of key material are baked
// in at build time from an out-of-source key file (see `build.rs` and the
// `keys/` folder), exposed here as `NGE_KEY_MATERIAL`. That keeps the key out of
// the committed code, so cloning the repo alone doesn't hand over the key — the
// repo owner decides whether to ship the real key, a test key, or none. It
// remains obfuscation, not a security boundary: a shipped binary still contains
// the key, and anyone who extracts it can open bundles (see the module
// threat-model note).

// Generated by build.rs: `pub(crate) const NGE_KEY_MATERIAL: [u8; 64] = [...];`
include!(concat!(env!("OUT_DIR"), "/nge_key.rs"));

fn master_key() -> [u8; 32] {
    use std::sync::OnceLock;
    static CACHED: OnceLock<[u8; 32]> = OnceLock::new();
    *CACHED.get_or_init(|| {
        // Fold the two halves of the material together and run it through
        // BLAKE3's KDF. (This matches the previous in-source fragment scheme
        // byte-for-byte, so bundles packed before the key moved still open.)
        let mut material = NGE_KEY_MATERIAL;
        for i in 0..32 {
            material[i] ^= material[32 + i];
        }
        blake3::derive_key("nge.master.v1", &material[..32])
    })
}

fn derive_nonce(header_nonce: &[u8; 12], label: &str) -> [u8; 12] {
    let mut material = Vec::with_capacity(32 + 12 + label.len());
    material.extend_from_slice(&master_key());
    material.extend_from_slice(header_nonce);
    material.extend_from_slice(label.as_bytes());
    let full = blake3::derive_key("nge.entry-nonce.v1", &material);
    let mut nonce = [0u8; 12];
    nonce.copy_from_slice(&full[..12]);
    nonce
}

/// Label used to derive the manifest's own nonce. Starts with a NUL so it can
/// never collide with a real entry name (which is `[A-Za-z0-9._-]`).
const MANIFEST_NONCE_LABEL: &str = "\0manifest";

fn cipher() -> ChaCha20Poly1305 {
    let key = master_key();
    ChaCha20Poly1305::new(Key::from_slice(&key))
}

fn short_blake3(bytes: &[u8]) -> String {
    blake3::hash(bytes).to_hex()[..32].to_string()
}

// ─── Building ────────────────────────────────────────────────────────────────

/// Build a `.nge` from a song's `file_hash`, its metadata, and its named
/// entries (e.g. `("instrumental.mp3", bytes)`). Entries are written in the
/// order given; that same order defines the bulk layout.
pub fn build_nge(
    file_hash: &str,
    metadata: serde_json::Value,
    entries: &[(String, Vec<u8>)],
) -> Result<Vec<u8>, NightingaleError> {
    let manifest_entries: Vec<ManifestEntry> = entries
        .iter()
        .map(|(name, bytes)| ManifestEntry {
            name: name.clone(),
            length: bytes.len() as u64,
            blake3: short_blake3(bytes),
        })
        .collect();

    let manifest = Manifest {
        version: 1,
        file_hash: file_hash.to_string(),
        metadata,
        entries: manifest_entries,
    };
    let manifest_json = serde_json::to_vec(&manifest)?;

    let header_nonce: [u8; 12] = rand::random();
    let aead = cipher();

    let manifest_nonce = derive_nonce(&header_nonce, MANIFEST_NONCE_LABEL);
    let manifest_ct = aead
        .encrypt(Nonce::from_slice(&manifest_nonce), manifest_json.as_slice())
        .map_err(|_| NightingaleError::Other("nge: manifest encryption failed".into()))?;

    if manifest_ct.len() as u64 > MAX_MANIFEST_LEN as u64 {
        return Err(NightingaleError::Other(
            "nge: manifest too large to encode".into(),
        ));
    }

    let mut out = Vec::new();
    out.extend_from_slice(NGE_MAGIC);
    out.push(NGE_VERSION);
    out.push(CIPHER_CHACHA20POLY1305);
    out.extend_from_slice(&header_nonce);
    out.extend_from_slice(&(manifest_ct.len() as u32).to_le_bytes());
    out.extend_from_slice(&manifest_ct);

    for (name, bytes) in entries {
        let nonce = derive_nonce(&header_nonce, name);
        let ct = aead
            .encrypt(Nonce::from_slice(&nonce), bytes.as_slice())
            .map_err(|_| NightingaleError::Other(format!("nge: encryption failed for {name}")))?;
        out.extend_from_slice(&ct);
    }

    Ok(out)
}

// ─── Reading ───────────────────────────────────────────────────────────────

/// An opened `.nge` with its manifest already decrypted. Holds the path and the
/// offsets needed to decrypt any single entry on demand without re-reading the
/// header. Cheap to clone-cache per song.
#[derive(Debug, Clone)]
pub struct NgeFile {
    pub path: PathBuf,
    pub manifest: Manifest,
    header_nonce: [u8; 12],
    bulk_start: u64,
}

fn parse_header(bytes: &[u8]) -> Result<([u8; 12], u32), NightingaleError> {
    if bytes.len() < HEADER_LEN {
        return Err(NightingaleError::Other(
            "nge: file shorter than header".into(),
        ));
    }
    if &bytes[0..4] != NGE_MAGIC {
        return Err(NightingaleError::Other("nge: bad magic".into()));
    }
    if bytes[4] != NGE_VERSION {
        return Err(NightingaleError::Other(format!(
            "nge: unsupported version {}",
            bytes[4]
        )));
    }
    if bytes[5] != CIPHER_CHACHA20POLY1305 {
        return Err(NightingaleError::Other(format!(
            "nge: unsupported cipher {}",
            bytes[5]
        )));
    }
    let mut header_nonce = [0u8; 12];
    header_nonce.copy_from_slice(&bytes[6..18]);
    let manifest_len = u32::from_le_bytes([bytes[18], bytes[19], bytes[20], bytes[21]]);
    if manifest_len > MAX_MANIFEST_LEN {
        return Err(NightingaleError::Other(
            "nge: manifest length too large".into(),
        ));
    }
    Ok((header_nonce, manifest_len))
}

impl NgeFile {
    /// Open a `.nge`, validate the header, and decrypt its manifest. Reads only
    /// the header plus the (small) manifest — never the bulk.
    pub fn open(path: &Path) -> Result<Self, NightingaleError> {
        let mut file = std::fs::File::open(path)?;
        let mut head = [0u8; HEADER_LEN];
        file.read_exact(&mut head)?;
        let (header_nonce, manifest_len) = parse_header(&head)?;

        let mut manifest_ct = vec![0u8; manifest_len as usize];
        file.read_exact(&mut manifest_ct)?;

        let aead = cipher();
        let manifest_nonce = derive_nonce(&header_nonce, MANIFEST_NONCE_LABEL);
        let manifest_json = aead
            .decrypt(Nonce::from_slice(&manifest_nonce), manifest_ct.as_slice())
            .map_err(|_| NightingaleError::Other("nge: manifest authentication failed".into()))?;
        let manifest: Manifest = serde_json::from_slice(&manifest_json)?;

        let bulk_start = HEADER_LEN as u64 + manifest_len as u64;
        Ok(Self {
            path: path.to_path_buf(),
            manifest,
            header_nonce,
            bulk_start,
        })
    }

    /// Byte offset (from file start) of the ciphertext for `name`, or `None` if
    /// the entry isn't in the manifest.
    fn entry_offset(&self, name: &str) -> Option<u64> {
        let mut offset = self.bulk_start;
        for entry in &self.manifest.entries {
            if entry.name == name {
                return Some(offset);
            }
            offset += entry.length + TAG_LEN;
        }
        None
    }

    /// Decrypt a single entry fully into memory and verify its BLAKE3. Audio,
    /// stems, cover and transcript are all small enough for this; video is too,
    /// just heavier.
    pub fn read_entry(&self, name: &str) -> Result<Vec<u8>, NightingaleError> {
        let entry = self
            .manifest
            .entry(name)
            .ok_or_else(|| NightingaleError::Other(format!("nge: no entry named {name}")))?;
        let offset = self
            .entry_offset(name)
            .ok_or_else(|| NightingaleError::Other(format!("nge: no entry named {name}")))?;

        let ct_len = entry.length + TAG_LEN;
        let mut file = std::fs::File::open(&self.path)?;
        file.seek(SeekFrom::Start(offset))?;
        let mut ct = vec![0u8; ct_len as usize];
        file.read_exact(&mut ct)?;

        let aead = cipher();
        let nonce = derive_nonce(&self.header_nonce, name);
        let plain = aead
            .decrypt(Nonce::from_slice(&nonce), ct.as_slice())
            .map_err(|_| {
                NightingaleError::Other(format!("nge: authentication failed for {name}"))
            })?;

        if short_blake3(&plain) != entry.blake3 {
            return Err(NightingaleError::Other(format!(
                "nge: blake3 mismatch for {name}"
            )));
        }
        Ok(plain)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    fn sample() -> (serde_json::Value, Vec<(String, Vec<u8>)>) {
        let metadata = serde_json::json!({
            "title": "Test", "artist": "Nobody", "album": "Demo",
            "duration_secs": 3.0, "is_analyzed": true,
        });
        let entries = vec![
            ("instrumental.mp3".to_string(), vec![1u8; 5000]),
            ("vocals.mp3".to_string(), vec![2u8; 4096]),
            ("cover.jpg".to_string(), vec![3u8; 1234]),
        ];
        (metadata, entries)
    }

    #[test]
    fn roundtrip_manifest_and_entries() {
        let (metadata, entries) = sample();
        let bytes = build_nge("abc123", metadata, &entries).unwrap();
        assert!(is_nge(&bytes));

        let dir = std::env::temp_dir().join(format!("nge-test-{}", rand::random::<u64>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("x.nge");
        std::fs::write(&path, &bytes).unwrap();

        let nge = NgeFile::open(&path).unwrap();
        assert_eq!(nge.manifest.file_hash, "abc123");
        assert_eq!(nge.manifest.entries.len(), 3);

        for (name, data) in &entries {
            let got = nge.read_entry(name).unwrap();
            assert_eq!(&got, data, "entry {name} mismatch");
        }
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn unknown_entry_errors() {
        let (metadata, entries) = sample();
        let bytes = build_nge("h", metadata, &entries).unwrap();
        let dir = std::env::temp_dir().join(format!("nge-test-{}", rand::random::<u64>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("x.nge");
        std::fs::write(&path, &bytes).unwrap();
        let nge = NgeFile::open(&path).unwrap();
        assert!(nge.read_entry("missing.mp3").is_err());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn corrupt_entry_fails_auth() {
        let (metadata, entries) = sample();
        let mut bytes = build_nge("h", metadata, &entries).unwrap();
        // Flip a byte deep in the bulk (well past the manifest).
        let last = bytes.len() - 1;
        bytes[last] ^= 0xff;
        let dir = std::env::temp_dir().join(format!("nge-test-{}", rand::random::<u64>()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("x.nge");
        std::fs::write(&path, &bytes).unwrap();
        let nge = NgeFile::open(&path).unwrap();
        // The tampered entry must fail; an untampered earlier entry still works.
        assert!(nge.read_entry("cover.jpg").is_err());
        assert!(nge.read_entry("instrumental.mp3").is_ok());
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn not_nge_is_rejected() {
        assert!(!is_nge(b"PK\x03\x04"));
        assert!(parse_header(b"not a real header at all").is_err());
    }
}
